"""empty message

Revision ID: 347e5f57a535
Revises: c4665f069b0a
Create Date: 2021-03-29 22:37:13.289244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347e5f57a535'
down_revision = 'c4665f069b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
