"""empty message

Revision ID: bf935ad2769c
Revises: edffda4d451a
Create Date: 2021-04-06 22:09:00.703751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf935ad2769c'
down_revision = 'edffda4d451a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.String(), nullable=False))
    op.add_column('Show', sa.Column('venue_name', sa.String(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###
