"""empty message

Revision ID: e14512153ffc
Revises: 450cfd8728e6
Create Date: 2021-03-15 23:21:06.587568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14512153ffc'
down_revision = '450cfd8728e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genres_items')
    op.drop_table('Genres')
    op.add_column('Venue', sa.Column('genres', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.create_table('Genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genres_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Genres_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Genres_items',
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Genres_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Genres_id'], ['Genres.id'], name='Genres_items_Genres_id_fkey'),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='Genres_items_Venue_id_fkey'),
    sa.PrimaryKeyConstraint('Venue_id', 'Genres_id', name='Genres_items_pkey')
    )
    # ### end Alembic commands ###
