"""empty message

Revision ID: fc948683a28b
Revises: ba91f9ad2539
Create Date: 2021-04-02 18:21:33.583583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc948683a28b'
down_revision = 'ba91f9ad2539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('datetime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'datetime')
    # ### end Alembic commands ###
